# docker-compose.db.yaml
# - - - - - - - - ДЛЯ ЛОКАЛЬНОЙ РАЗРАБОТКИ - - - - - - - -  
 
# version: '3.8'

services:
  db:
    image: postgres:16.1-alpine3.19
    container_name: koshka-musya-db-debug
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./_data/pgdata:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
